src_fmt:
  cache/Illinois_thermal_w{win:d}/{mag}a{aspin:g}_i{inc:d}/summ_Rh{Rhigh:d}_{freq}.tsv
dst_fmt:
  cache/Illinois_thermal_w{win:d}/stat_{freq}_{type}.tsv
freqs:
  - 86GHz
  - 230GHz
  - 2um
  - xray
